project:
  type: book
  output-dir: docs

book:
  title: "How to Visualize"
  author: "Rethink Priorities"
  repo-url: https://github.com/rethinkpriorities/how-to-visualize/
  repo-actions: [edit, issue]
  date: today
  chapters:
    - index.qmd
    - chapters/best-practices.qmd
    - chapters/basic-plots.qmd
    - chapters/likert-plots.qmd
    - chapters/labels.qmd
    - chapters/tips-tricks.qmd
    - references.qmd
  reader-mode: true

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    citations-hover: true
    footnotes-hover: true

editor: visual
freeze: true
