project:
  type: book
  output-dir: docs

book:
  title: "How to Visualize"
  author: "Rethink Priorities"
  repo-url: https://github.com/rethinkpriorities/how-to-visualize/
  repo-actions: [edit, issue]
  date: today
  chapters:
    - index.qmd
    - chapters/best-practices.qmd
    - part: chapters/basic-plots.qmd
      chapters:
        - chapters/basic-plots/bar-plots.qmd
        - chapters/basic-plots/scatter-plots.qmd
    - part: chapters/advanced-plots.qmd
      chapters:
        - chapters/advanced-plots/likert-plots.qmd
    - chapters/labels.qmd
    - chapters/tips-tricks.qmd
  reader-mode: true

comments:
  hypothesis: false

format:
  html:
    code-fold: true
    code-link: true
    citations-hover: true
    footnotes-hover: true
    fig-format: svg

editor: visual
freeze: true
