# Good practice: coding, labelling, etc

**Coding, labelling, other good practices in general**

## Coding for visualisations^[DR: These are my proposed approaches, but I'm not dogmatic, and you may know better]

**ggplot is king**

Use `ggplot` always unless you've a strong reason to do otherwise. Always save the plot as an object in the environment as well as printing it where it belongs.

'Piping data into the ggplot' to make the code more portable and readable. Keep steps separate.

\

**Automate and try to keep code clean and mental overhead low**

Ideally, we will come up with a set of functions and default options for the key sets of plots we use and like. Otherwise define sets of common options for plots in one place, and repeated ggplot elements together as a list

-   to avoid repetition and clutter

-   to allow easy 'global' adjustment

However, there are times in which too much automation makes things less flexible and increases mental overhead. We'll come to good compromises.


## Labeling {-}

Use readable but concise labels. "Amount donated" is OK, "GWWC" is OK because we assume people know what GWWC is from context.

`amt_don` is not OK. Pete will yell at you.

Coding-wise: Define and reuse lists of labels (or use inherent labeling options where these exist, to exploit existing variable and value labels.)
